FROM python:3.12-slim AS builder

WORKDIR /src
COPY . .
RUN pip install --no-cache-dir mkdocs mkdocs-material \
    && bash build.sh

FROM nginx:alpine

COPY --from=builder /src/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
