package kg.apc.jmeter.plugins.importer;

import kg.apc.jmeter.plugins.importer.model.RequestModel;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Converts a list of {@link RequestModel} instances into a JMeter Test Plan (.jmx).
 *
 * <p>Each request produces an {@code HTTPSamplerProxy} with:
 * protocol, server hostname/IP, port, method, path, body data,
 * query-parameter arguments, and a per-sampler {@code HeaderManager}
 * containing all captured request headers.
 * Everything is wrapped in a Thread Group under the Test Plan element
 * so the generated JMX is immediately runnable in JMeter.</p>
 */
public class JMeterTestPlanBuilder {

    /**
     * Build a JMX XML string from the supplied requests.
     *
     * @param requests    list of parsed request models
     * @param planName    name of the Test Plan element
     * @param threadCount number of virtual users (threads) in the Thread Group
     * @return JMX XML as a {@link String}
     */
    public String buildJmx(List<RequestModel> requests,
                            String planName,
                            int    threadCount) {
        StringWriter sw = new StringWriter();
        PrintWriter  pw = new PrintWriter(sw);

        pw.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        pw.println("<jmeterTestPlan version=\"1.2\" properties=\"5.0\" jmeter=\"5.6.3\">");
        pw.println("  <hashTree>");

        // ---- Test Plan -----------------------------------------------------
        pw.printf("    <TestPlan guiclass=\"TestPlanGui\" testclass=\"TestPlan\"%n");
        pw.printf("              testname=\"%s\" enabled=\"true\">%n", xmlEscape(planName));
        pw.println("      <stringProp name=\"TestPlan.comments\">Generated by Swagger/Postman Importer</stringProp>");
        pw.println("      <boolProp name=\"TestPlan.functional_mode\">false</boolProp>");
        pw.println("      <boolProp name=\"TestPlan.serialize_threadgroups\">false</boolProp>");
        pw.println("      <elementProp name=\"TestPlan.user_defined_variables\"");
        pw.println("                   elementType=\"Arguments\" guiclass=\"ArgumentsPanel\"");
        pw.println("                   testclass=\"Arguments\" testname=\"User Defined Variables\" enabled=\"true\">");
        pw.println("        <collectionProp name=\"Arguments.arguments\"/>");
        pw.println("      </elementProp>");
        pw.println("    </TestPlan>");
        pw.println("    <hashTree>");

        // ---- Thread Group --------------------------------------------------
        pw.println("      <ThreadGroup guiclass=\"ThreadGroupGui\" testclass=\"ThreadGroup\"");
        pw.println("                   testname=\"Thread Group\" enabled=\"true\">");
        pw.println("        <stringProp name=\"ThreadGroup.on_sample_error\">continue</stringProp>");
        pw.println("        <elementProp name=\"ThreadGroup.main_controller\"");
        pw.println("                     elementType=\"LoopController\" guiclass=\"LoopControlPanel\"");
        pw.println("                     testclass=\"LoopController\" testname=\"Loop Controller\" enabled=\"true\">");
        pw.println("          <boolProp name=\"LoopController.continue_forever\">false</boolProp>");
        pw.println("          <stringProp name=\"LoopController.loops\">1</stringProp>");
        pw.println("        </elementProp>");
        pw.printf( "        <stringProp name=\"ThreadGroup.num_threads\">%d</stringProp>%n", threadCount);
        pw.println("        <stringProp name=\"ThreadGroup.ramp_time\">1</stringProp>");
        pw.println("        <boolProp name=\"ThreadGroup.scheduler\">false</boolProp>");
        pw.println("        <stringProp name=\"ThreadGroup.duration\"></stringProp>");
        pw.println("        <stringProp name=\"ThreadGroup.delay\"></stringProp>");
        pw.println("        <boolProp name=\"ThreadGroup.same_user_on_next_iteration\">true</boolProp>");
        pw.println("      </ThreadGroup>");
        pw.println("      <hashTree>");

        // ---- HTTP Samplers -------------------------------------------------
        for (RequestModel req : requests) {
            addHttpSampler(pw, req);
        }

        pw.println("      </hashTree>");   // Thread Group hashTree
        pw.println("    </hashTree>");     // Test Plan hashTree
        pw.println("  </hashTree>");       // root
        pw.println("</jmeterTestPlan>");

        pw.flush();
        return sw.toString();
    }

    /**
     * Build JMX and write it directly to a file.
     *
     * @param requests    list of parsed request models
     * @param planName    name of the Test Plan element
     * @param threadCount number of virtual users (threads)
     * @param outputPath  absolute path of the output .jmx file
     * @throws IOException on write failure
     */
    public void writeJmx(List<RequestModel> requests,
                         String planName,
                         int    threadCount,
                         String outputPath) throws IOException {
        Files.write(Paths.get(outputPath),
                    buildJmx(requests, planName, threadCount)
                        .getBytes(StandardCharsets.UTF_8));
    }

    // -----------------------------------------------------------------------
    // HTTP Sampler
    // -----------------------------------------------------------------------

    private void addHttpSampler(PrintWriter pw, RequestModel req) {
        String samplerName = xmlEscape(nvl(req.getName(), "HTTP Request"));
        String protocol    = nvl(req.getProtocol(), "http");
        String host        = nvl(req.getHost(), "localhost");
        String portStr     = req.getPort() > 0 ? String.valueOf(req.getPort()) : "";
        String method      = nvl(req.getMethod(), "GET");
        String path        = nvl(req.getPath(), "/");
        boolean hasBody    = req.getBodyData() != null && !req.getBodyData().isEmpty();
        String  ct         = nvl(req.getContentType(), "");

        pw.println("        <HTTPSamplerProxy guiclass=\"HttpTestSampleGui\"");
        pw.println("                          testclass=\"HTTPSamplerProxy\"");
        pw.printf( "                          testname=\"%s\" enabled=\"true\">%n", samplerName);

        // Body / query arguments
        if (hasBody && ct.contains("urlencoded")) {
            pw.println("          <boolProp name=\"HTTPSampler.postBodyRaw\">false</boolProp>");
            pw.println("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\"");
            pw.println("                       guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\"");
            pw.println("                       testname=\"User Defined Variables\" enabled=\"true\">");
            pw.println("            <collectionProp name=\"Arguments.arguments\">");
            for (String pair : req.getBodyData().split("&")) {
                String[] kv = pair.split("=", 2);
                String argName = xmlEscape(kv[0]);
                pw.printf( "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">%n", argName);
                pw.println("                <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>");
                pw.printf( "                <stringProp name=\"Argument.value\">%s</stringProp>%n",
                           kv.length > 1 ? xmlEscape(kv[1]) : "");
                pw.println("                <stringProp name=\"Argument.metadata\">=</stringProp>");
                pw.println("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>");
                pw.printf( "                <stringProp name=\"Argument.name\">%s</stringProp>%n", argName);
                pw.println("              </elementProp>");
            }
            pw.println("            </collectionProp>");
            pw.println("          </elementProp>");
        } else if (hasBody) {
            pw.println("          <boolProp name=\"HTTPSampler.postBodyRaw\">true</boolProp>");
            pw.println("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\"");
            pw.println("                       guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\"");
            pw.println("                       testname=\"User Defined Variables\" enabled=\"true\">");
            pw.println("            <collectionProp name=\"Arguments.arguments\">");
            pw.println("              <elementProp name=\"\" elementType=\"HTTPArgument\">");
            pw.println("                <boolProp name=\"HTTPArgument.always_encode\">false</boolProp>");
            pw.printf( "                <stringProp name=\"Argument.value\">%s</stringProp>%n",
                       xmlEscape(req.getBodyData()));
            pw.println("                <stringProp name=\"Argument.metadata\">=</stringProp>");
            pw.println("              </elementProp>");
            pw.println("            </collectionProp>");
            pw.println("          </elementProp>");
        } else {
            // GET-style query params via Arguments
            pw.println("          <boolProp name=\"HTTPSampler.postBodyRaw\">false</boolProp>");
            pw.println("          <elementProp name=\"HTTPsampler.Arguments\" elementType=\"Arguments\"");
            pw.println("                       guiclass=\"HTTPArgumentsPanel\" testclass=\"Arguments\"");
            pw.println("                       testname=\"User Defined Variables\" enabled=\"true\">");
            pw.println("            <collectionProp name=\"Arguments.arguments\">");
            for (RequestModel.ParamEntry qp : req.getQueryParams()) {
                String argName = xmlEscape(qp.getName());
                pw.printf( "              <elementProp name=\"%s\" elementType=\"HTTPArgument\">%n", argName);
                pw.println("                <boolProp name=\"HTTPArgument.always_encode\">true</boolProp>");
                pw.printf( "                <stringProp name=\"Argument.value\">%s</stringProp>%n",
                           xmlEscape(qp.getValue()));
                pw.println("                <stringProp name=\"Argument.metadata\">=</stringProp>");
                pw.println("                <boolProp name=\"HTTPArgument.use_equals\">true</boolProp>");
                pw.printf( "                <stringProp name=\"Argument.name\">%s</stringProp>%n", argName);
                pw.println("              </elementProp>");
            }
            pw.println("            </collectionProp>");
            pw.println("          </elementProp>");
        }

        // Core connection details
        pw.printf("          <stringProp name=\"HTTPSampler.domain\">%s</stringProp>%n",   xmlEscape(host));
        pw.printf("          <stringProp name=\"HTTPSampler.port\">%s</stringProp>%n",     portStr);
        pw.printf("          <stringProp name=\"HTTPSampler.protocol\">%s</stringProp>%n", xmlEscape(protocol));
        pw.printf("          <stringProp name=\"HTTPSampler.path\">%s</stringProp>%n",
                  xmlEscape(appendQueryToPath(path, req, hasBody)));
        pw.printf("          <stringProp name=\"HTTPSampler.method\">%s</stringProp>%n",   xmlEscape(method));
        pw.println("          <boolProp name=\"HTTPSampler.follow_redirects\">true</boolProp>");
        pw.println("          <boolProp name=\"HTTPSampler.auto_redirects\">false</boolProp>");
        pw.println("          <boolProp name=\"HTTPSampler.use_keepalive\">true</boolProp>");
        pw.println("          <boolProp name=\"HTTPSampler.DO_MULTIPART_POST\">false</boolProp>");
        pw.println("          <stringProp name=\"HTTPSampler.connect_timeout\">5000</stringProp>");
        pw.println("          <stringProp name=\"HTTPSampler.response_timeout\">30000</stringProp>");
        pw.println("        </HTTPSamplerProxy>");

        // Header Manager (child element — must be inside sampler's own hashTree)
        if (!req.getHeaders().isEmpty()) {
            pw.println("        <hashTree>");
            pw.println("          <HeaderManager guiclass=\"HeaderPanel\" testclass=\"HeaderManager\"");
            pw.printf( "                         testname=\"HTTP Header Manager - %s\" enabled=\"true\">%n",
                       samplerName);
            pw.println("            <collectionProp name=\"HeaderManager.headers\">");
            for (RequestModel.HeaderEntry h : req.getHeaders()) {
                String hName = xmlEscape(h.getName());
                pw.printf( "              <elementProp name=\"%s\" elementType=\"Header\">%n", hName);
                pw.printf( "                <stringProp name=\"Header.name\">%s</stringProp>%n", hName);
                pw.printf( "                <stringProp name=\"Header.value\">%s</stringProp>%n",
                           xmlEscape(h.getValue()));
                pw.println("              </elementProp>");
            }
            pw.println("            </collectionProp>");
            pw.println("          </HeaderManager>");
            pw.println("          <hashTree/>");
            pw.println("        </hashTree>");
        } else {
            pw.println("        <hashTree/>");
        }
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /**
     * When body is present, query params are appended directly to the path
     * string rather than using the HTTPArgument list (which is used for body).
     */
    private String appendQueryToPath(String path, RequestModel req, boolean hasBody) {
        if (!hasBody || req.getQueryParams().isEmpty()) return path;
        StringBuilder sb = new StringBuilder(path);
        // Check if path already contains query parameters
        if (!path.contains("?")) {
            sb.append('?');
        } else {
            sb.append('&');
        }
        boolean first = !path.contains("?");
        for (RequestModel.ParamEntry qp : req.getQueryParams()) {
            if (!first) sb.append('&');
            first = false;
            try {
                String encodedName = java.net.URLEncoder.encode(qp.getName(), "UTF-8");
                String encodedValue = java.net.URLEncoder.encode(qp.getValue(), "UTF-8");
                sb.append(encodedName).append('=').append(encodedValue);
            } catch (java.io.UnsupportedEncodingException e) {
                // UTF-8 is always supported
                sb.append(qp.getName()).append('=').append(qp.getValue());
            }
        }
        return sb.toString();
    }

    private static String nvl(String s, String def) {
        return (s != null && !s.isEmpty()) ? s : def;
    }

    private static String xmlEscape(String s) {
        if (s == null) return "";
        return s.replace("&",  "&amp;")
                .replace("<",  "&lt;")
                .replace(">",  "&gt;")
                .replace("\"", "&quot;")
                .replace("'",  "&apos;");
    }
}
