package kg.apc.jmeter.vizualizers;

/**
 *
 * @author Stéphane Hoblingre
 */
public class JSettingsPanel extends javax.swing.JPanel {

    private AbstractGraphPanelVisualizer parent = null;

    /** Creates new form JSettingsPanel */
    public JSettingsPanel(AbstractGraphPanelVisualizer parent) {
        initComponents();
        this.parent = parent;
    }

    public void setGranulationValue(int value) {
        if(value == 500) jSliderGranulation.setValue(0);
        else if(value <= 5000) jSliderGranulation.setValue(value / 1000);
        else jSliderGranulation.setValue((value / 10000) + 5);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGranulation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSliderGranulation = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kg/apc/jmeter/vizualizers/logoSimple.png"))); // NOI18N
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Timeline Settings"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Group values for:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel3.add(jLabel2, gridBagConstraints);

        jTextFieldGranulation.setEditable(false);
        jTextFieldGranulation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldGranulation.setText("1000");
        jTextFieldGranulation.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextFieldGranulation.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextFieldGranulation.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel3.add(jTextFieldGranulation, gridBagConstraints);

        jLabel3.setText("ms.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanel3.add(jLabel3, gridBagConstraints);

        jSliderGranulation.setMaximum(11);
        jSliderGranulation.setMinorTickSpacing(1);
        jSliderGranulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderGranulationMouseReleased(evt);
            }
        });
        jSliderGranulation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderGranulationStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jSliderGranulation, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderGranulationMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jSliderGranulationMouseReleased
    {//GEN-HEADEREND:event_jSliderGranulationMouseReleased
        parent.setGranulation(getGranulationFromSliderValue(jSliderGranulation.getValue()));
    }//GEN-LAST:event_jSliderGranulationMouseReleased

    private int getGranulationFromSliderValue(int value) {
        int grpValue = 0;
        if( value == 0) grpValue = 500;
        else if(value < 6) grpValue = 1000*value;
        else grpValue = 10000*(value-5);

        return grpValue;
    }

    private void jSliderGranulationStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderGranulationStateChanged
    {//GEN-HEADEREND:event_jSliderGranulationStateChanged
        jTextFieldGranulation.setText(Integer.toString(getGranulationFromSliderValue(jSliderGranulation.getValue())));
    }//GEN-LAST:event_jSliderGranulationStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSliderGranulation;
    private javax.swing.JTextField jTextFieldGranulation;
    // End of variables declaration//GEN-END:variables

}
