name: Build Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.24.0
      with:
        php-version: '5.6'
        tools: composer

    - name: Prepare upload
      run: ./prepare-upload.sh

    - name: Maven tests
      run: mvn -T 1C -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true --fail-at-end --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report install

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1

    - name: Perform upload
      run: 'curl --fail -vk https://jmeter-plugins.org/unzip.php -F "zipfile=@upload/site.zip" -H "Authorization: Bearer ${{ secrets.UPLOAD_TOKEN }}"'
      if: github.ref == 'refs/heads/master'

